version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - reddit_frontend
      - reddit_backend
  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - reddit_frontend
      - reddit_backend

  elasticsearch:
    image: elasticsearch:7.4.0
    expose:
      - 9200
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
      
    ports:
      - "9200:9200"
    networks:
      - reddit_frontend
      - reddit_backend

  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"
    networks:
      - reddit_frontend
      - reddit_backend
networks:
  reddit_frontend:
  reddit_backend:
